import React, { createContext, useContext, useEffect, useState } from 'react';

const AppSettingsContext = createContext();

const STORAGE_KEYS = {
  theme: 'sofiTheme',
  locale: 'sofiLocale',
};

const translations = {
  es: {
    appName: 'SOFI',
    activeUser: 'Usuario activo',
    guestUser: 'Invitado',
    logout: 'Cerrar sesión',
    dayMode: 'Día',
    nightMode: 'Noche',
    switchToDark: 'Activar modo noche',
    switchToLight: 'Activar modo día',
    languageLabel: 'Idioma',
    loginTitle: 'Bienvenido de nuevo',
    registerTitle: 'Crea tu cuenta profesional',
    forgotTitle: 'Recupera el acceso',
    loginSubtitle: 'Ingresa con tu correo y contraseña.',
    registerSubtitle: 'Regístrate rápido y comienza a publicar.',
    forgotSubtitle: 'Te enviaremos un enlace para restablecer tu contraseña.',
    nameLabel: 'Nombre',
    namePlaceholder: 'Ej. Ana Márquez',
    emailLabel: 'Correo electrónico',
    emailPlaceholder: 'correo@empresa.com',
    passwordLabel: 'Contraseña',
    passwordPlaceholder: '••••••••',
    loginButton: 'Ingresar',
    registerButton: 'Registrarse',
    sendLinkButton: 'Enviar enlace',
    continueWith: 'o continúa con',
    googleButton: 'Google',
    microsoftButton: 'Microsoft',
    noAccount: '¿No tienes una cuenta?',
    alreadyAccount: '¿Ya tienes una cuenta?',
    signUpHere: 'Regístrate aquí',
    logIn: 'Inicia sesión',
    forgotPassword: '¿Olvidaste tu contraseña?',
    roleRecruiter: 'Reclutador',
    dashboardPanel: 'Panel de control',
    dashboardTitle: 'Bienvenido a Sofi',
    dashboardSubtitle: 'Gestiona vacantes, crea perfiles con IA y publica en portales desde un solo lugar.',
    publishVacancy: '✦ Publicar vacante',
    activeVacancies: 'Vacantes activas',
    profilesCreated: 'Perfiles IA creados',
    campaignsPublished: 'Campañas publicadas',
    publicationTitle: 'Publicación de vacantes de empleo',
    publicationSubtitle: 'Define el perfil, elige portales y publica tu vacante en un flujo claro.',
    menuLabel: 'Menú',
    publicationNav: 'Publicación',
    dashboardNav: 'Panel',
    guideNav: 'Guía',
    guideTitle: 'Guía rápida',
    guideSubtitle: 'Flujo recomendado para publicar una vacante sin perder pasos.',
    guideStep1: 'Crea o selecciona una vacante vigente.',
    guideStep2: 'Completa el perfil del anuncio y revisa la vista previa.',
    guideStep3: 'Elige países y portales según costo y alcance.',
    guideStep4: 'Confirma la publicación y revisa el estado por portal.',
    loading: 'Cargando...',
    stepVacancy: 'Vacante',
    stepProfile: 'Perfil',
    stepPortals: 'Portales',
    stepPublish: 'Publicar',
    stepLabel: 'Paso',
    stepVacancyDescription: 'Elige una vacante existente o crea una nueva.',
    stepProfileDescription: 'Define el anuncio, salario, ubicacion y requisitos.',
    stepPortalsDescription: 'Selecciona paises y portales donde se publicara.',
    stepPublishDescription: 'Revisa el resumen final y confirma la publicacion.',
    selectVacancyTitle: 'Selecciona la vacante a publicar',
    existingVacancies: 'Vacantes existentes',
    createNewVacancy: '+ Crear nueva vacante',
    searchVacancyPlaceholder: 'Buscar por nombre, codigo o empresa...',
    all: 'Todas',
    active: 'Activas',
    unpublished: 'Sin publicar',
    loadingVacancies: 'Cargando vacantes...',
    noVacanciesFound: 'No se encontraron vacantes',
    createVacancyError: 'No se pudo guardar la vacante',
    code: 'Codigo',
    name: 'Nombre',
    company: 'Empresa',
    category: 'Categoria',
    status: 'Estado',
    assignedCode: 'Codigo asignado automaticamente',
    vacancyName: 'Nombre de la vacante',
    vacancyNamePlaceholder: 'Ej. Gerente de Ventas Regional',
    selectCompany: 'Selecciona empresa',
    selectCategory: 'Selecciona categoria',
    draft: 'Borrador',
    draftHelp: 'Guardado, no visible aun',
    current: 'Vigente',
    currentHelp: 'Activa y lista para publicar',
    viewExistingVacancies: 'Ver vacantes existentes',
    saveDraft: 'Guardar como borrador',
    saveAndContinue: 'Guardar y continuar',
    selectedVacancy: 'Vacante seleccionada',
    continue: 'Continuar',
    selectVacancyToContinue: 'Selecciona una vacante de la lista para continuar.',
    preview: 'Vista previa',
    jobNamePlaceholder: 'Nombre del cargo...',
    requiredFields: 'Campos requeridos',
    saveOnly: 'Solo guardar',
    profileTitle: 'Perfil del candidato',
    generating: 'Generando...',
    generateWithAI: 'Generar con IA',
    previewAd: 'Previsualizar aviso',
    aiAssistantTitle: 'Sofi IA - Asistente de perfiles',
    aiAssistantText: 'Sofi generara automaticamente un perfil ideal basado en el puesto y sector, optimizando la redaccion para atraer a los mejores candidatos en cada portal.',
    adTitle: 'Titulo del anuncio',
    adTitlePlaceholder: 'Ej. Vendedor(a) de Mostrador - Pasteleria SKIC',
    adTitleHint: 'Este es el titulo que veran los candidatos en los portales',
    scheduleType: 'Tipo de jornada',
    salaryRange: 'Salario (rango)',
    currency: 'Moneda',
    salaryPlaceholder: 'Ej. 8,000 - 10,500',
    location: 'Ubicacion',
    jobDescription: 'Descripcion del puesto',
    aiEditableNote: 'Texto generado por Sofi IA - puedes editarlo libremente',
    requirements: 'Requisitos',
    back: 'Regresar',
    continueSelectPortals: 'Continuar - Seleccionar portales',
    aiSuggestions: 'Sugerencias IA',
    sofiRecommendsInclude: 'Sofi recomienda incluir:',
    savedProfiles: 'Perfiles guardados',
    reuseProfiles: 'Reutiliza perfiles de campanas anteriores:',
    noSavedProfiles: 'No hay perfiles guardados.',
    usedInCampaigns: 'Usado en',
    campaigns: 'campanas',
    previewAdTitle: 'Previsualizacion del aviso',
    previewAdSubtitle: 'Asi veran los candidatos tu publicacion en los portales',
    portalView: 'Vista portal:',
    generic: 'Generico',
    companyLabel: 'Empresa',
    selectPortalsTitle: 'Seleccionar portales de publicacion',
    smartAISelection: 'Seleccion inteligente IA',
    portalsInfo: 'Sofi IA recomienda publicar en portales gratuitos primero para maximizar alcance sin costo. Los portales de pago incrementan visibilidad en perfiles mas especificos.',
    publicationCountries: 'Paises de publicacion',
    selectOneOrMoreCountries: 'Selecciona uno o mas paises',
    clear: 'Limpiar',
    apply: 'Aplicar',
    portals: 'portales',
    searchPortalPlaceholder: 'Buscar portal...',
    freeOnly: 'Solo gratis',
    paid: 'De pago',
    loadingPortals: 'Cargando portales...',
    noPortalsFound: 'No se encontraron portales para estos filtros.',
    portal: 'Portal',
    type: 'Tipo',
    companyModel: 'Modelo empresa',
    estimatedCostShort: 'Costo est.',
    free: 'Gratis',
    paidModel: 'Bolsa',
    paidCompanyModel: 'De paga',
    continueReviewPublish: 'Continuar - Revisar y publicar',
    costSummary: 'Resumen de costos',
    selectedPortals: 'Portales seleccionados',
    noPortalSelected: 'Ningun portal seleccionado',
    breakdown: 'Desglose',
    freeFreemiumPortals: 'Portales gratuitos/freemium',
    estimatedTotal: 'Total estimado',
    costWarning: 'Los costos son estimados. El costo final se confirma al publicar en cada portal.',
    aiRecommendation: 'Recomendacion IA',
    currentVacancyRecommendation: 'Para tu vacante actual, Sofi recomienda priorizar:',
    applySuggestedSelection: 'Aplicar seleccion sugerida',
    confirmPublishTitle: 'Confirmar y publicar',
    confirmPublishInfo: 'Revisa el resumen antes de publicar. Una vez confirmado, Sofi enviara la vacante a cada portal seleccionado.',
    vacancy: 'Vacante',
    noName: 'Sin nombre',
    noLocation: 'Sin ubicacion',
    selectedPortalsCount: 'portales seleccionados',
    publicationStatus: 'Estado de publicacion',
    pendingStart: 'Pendiente de inicio',
    queued: 'En cola',
    publishing: 'Publicando...',
    inProgress: 'En progreso',
    publishedOk: 'Publicado correctamente',
    published: 'Publicado',
    modifySelection: 'Modificar seleccion',
    startNewVacancy: 'Iniciar nueva vacante',
    processing: 'Procesando...',
    publishVacancyAction: 'Publicar vacante',
    finalSummary: 'Resumen final',
    freePortalsToPublish: 'Portales gratuitos a publicar',
    paidPortalsToPublish: 'Portales de pago a publicar',
    totalToPay: 'Total a pagar',
    paymentMethod: 'Metodo de pago',
    noPaymentRequired: 'No requiere pago',
    corporateCard: 'Tarjeta corporativa ****4821',
    bankTransfer: 'Transferencia bancaria',
    sofiCredit: 'Credito Sofi (saldo disponible: MX$ 5,000)',
    publicationValidity: 'Vigencia de publicaciones',
    paidPortalsPublishUntil: 'Los portales de pago publican hasta esta fecha',
    languageSwitch: 'Cambiar idioma',
    adminSignIn: 'Ingresar admin',
    restrictedAccess: 'Acceso restringido',
    credentialsSaved: 'Credenciales guardadas correctamente',
    credentialsSaveError: 'Error al guardar las credenciales',
    portalCredentialsHelp: 'Por favor ingresa tus credenciales para publicar en este portal.',
    usernameOrEmail: 'Usuario o correo',
    requiredField: 'Este campo es requerido',
    secureCredentials: 'Tus credenciales se almacenan de forma cifrada y segura.',
    cancel: 'Cancelar',
    saving: 'Guardando...',
    saveCredentials: 'Guardar credenciales',
  },
  en: {
    appName: 'SOFI',
    activeUser: 'Active user',
    guestUser: 'Guest',
    logout: 'Log out',
    dayMode: 'Day',
    nightMode: 'Night',
    switchToDark: 'Switch to dark mode',
    switchToLight: 'Switch to light mode',
    languageLabel: 'Language',
    loginTitle: 'Welcome back',
    registerTitle: 'Create your professional account',
    forgotTitle: 'Recover access',
    loginSubtitle: 'Sign in with your email and password.',
    registerSubtitle: 'Register quickly and start publishing.',
    forgotSubtitle: 'We will send you a link to reset your password.',
    nameLabel: 'Name',
    namePlaceholder: 'Ex. Ana Márquez',
    emailLabel: 'Email address',
    emailPlaceholder: 'email@company.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '••••••••',
    loginButton: 'Sign in',
    registerButton: 'Sign up',
    sendLinkButton: 'Send link',
    continueWith: 'or continue with',
    googleButton: 'Google',
    microsoftButton: 'Microsoft',
    noAccount: 'Don’t have an account?',
    alreadyAccount: 'Already have an account?',
    signUpHere: 'Sign up here',
    logIn: 'Log in',
    forgotPassword: 'Forgot your password?',
    roleRecruiter: 'Recruiter',
    dashboardPanel: 'Dashboard',
    dashboardTitle: 'Welcome to Sofi',
    dashboardSubtitle: 'Manage vacancies, create AI profiles, and publish on portals from one place.',
    publishVacancy: '✦ Publish vacancy',
    activeVacancies: 'Active vacancies',
    profilesCreated: 'AI profiles created',
    campaignsPublished: 'Campaigns published',
    publicationTitle: 'Portal publication',
    publicationSubtitle: 'Define the profile, choose portals, and publish your vacancy in a clear flow.',
    menuLabel: 'Menu',
    publicationNav: 'Publication',
    dashboardNav: 'Dashboard',
    guideNav: 'Guide',
    guideTitle: 'Quick guide',
    guideSubtitle: 'Recommended flow to publish a vacancy without missing steps.',
    guideStep1: 'Create or select an active vacancy.',
    guideStep2: 'Complete the ad profile and review the preview.',
    guideStep3: 'Choose countries and portals by cost and reach.',
    guideStep4: 'Confirm publication and review status by portal.',
    loading: 'Loading...',
    stepVacancy: 'Vacancy',
    stepProfile: 'Profile',
    stepPortals: 'Portals',
    stepPublish: 'Publish',
    stepLabel: 'Step',
    stepVacancyDescription: 'Choose an existing vacancy or create a new one.',
    stepProfileDescription: 'Define the ad, salary, location, and requirements.',
    stepPortalsDescription: 'Select countries and portals where it will be published.',
    stepPublishDescription: 'Review the final summary and confirm publication.',
    selectVacancyTitle: 'Select the vacancy to publish',
    existingVacancies: 'Existing vacancies',
    createNewVacancy: '+ Create new vacancy',
    searchVacancyPlaceholder: 'Search by name, code, or company...',
    all: 'All',
    active: 'Active',
    unpublished: 'Unpublished',
    loadingVacancies: 'Loading vacancies...',
    noVacanciesFound: 'No vacancies found',
    createVacancyError: 'Could not save vacancy',
    code: 'Code',
    name: 'Name',
    company: 'Company',
    category: 'Category',
    status: 'Status',
    assignedCode: 'Automatically assigned code',
    vacancyName: 'Vacancy name',
    vacancyNamePlaceholder: 'Ex. Regional Sales Manager',
    selectCompany: 'Select company',
    selectCategory: 'Select category',
    draft: 'Draft',
    draftHelp: 'Saved, not visible yet',
    current: 'Active',
    currentHelp: 'Active and ready to publish',
    viewExistingVacancies: 'View existing vacancies',
    saveDraft: 'Save as draft',
    saveAndContinue: 'Save and continue',
    selectedVacancy: 'Selected vacancy',
    continue: 'Continue',
    selectVacancyToContinue: 'Select a vacancy from the list to continue.',
    preview: 'Preview',
    jobNamePlaceholder: 'Job title...',
    requiredFields: 'Required fields',
    saveOnly: 'Save only',
    profileTitle: 'Candidate profile',
    generating: 'Generating...',
    generateWithAI: 'Generate with AI',
    previewAd: 'Preview ad',
    aiAssistantTitle: 'Sofi AI - Profile assistant',
    aiAssistantText: 'Sofi will automatically generate an ideal profile based on the role and sector, optimizing the wording to attract the best candidates on each portal.',
    adTitle: 'Ad title',
    adTitlePlaceholder: 'Ex. Counter Salesperson - SKIC Bakery',
    adTitleHint: 'This is the title candidates will see on the portals',
    scheduleType: 'Schedule type',
    salaryRange: 'Salary range',
    currency: 'Currency',
    salaryPlaceholder: 'Ex. 8,000 - 10,500',
    location: 'Location',
    jobDescription: 'Job description',
    aiEditableNote: 'Text generated by Sofi AI - you can edit it freely',
    requirements: 'Requirements',
    back: 'Back',
    continueSelectPortals: 'Continue - Select portals',
    aiSuggestions: 'AI suggestions',
    sofiRecommendsInclude: 'Sofi recommends including:',
    savedProfiles: 'Saved profiles',
    reuseProfiles: 'Reuse profiles from previous campaigns:',
    noSavedProfiles: 'No saved profiles.',
    usedInCampaigns: 'Used in',
    campaigns: 'campaigns',
    previewAdTitle: 'Ad preview',
    previewAdSubtitle: 'This is how candidates will see your publication on portals',
    portalView: 'Portal view:',
    generic: 'Generic',
    companyLabel: 'Company',
    selectPortalsTitle: 'Select publication portals',
    smartAISelection: 'Smart AI selection',
    portalsInfo: 'Sofi AI recommends publishing on free portals first to maximize reach at no cost. Paid portals increase visibility for more specific profiles.',
    publicationCountries: 'Publication countries',
    selectOneOrMoreCountries: 'Select one or more countries',
    clear: 'Clear',
    apply: 'Apply',
    portals: 'portals',
    searchPortalPlaceholder: 'Search portal...',
    freeOnly: 'Free only',
    paid: 'Paid',
    loadingPortals: 'Loading portals...',
    noPortalsFound: 'No portals found for these filters.',
    portal: 'Portal',
    type: 'Type',
    companyModel: 'Company model',
    estimatedCostShort: 'Est. cost',
    free: 'Free',
    paidModel: 'Job board',
    paidCompanyModel: 'Paid',
    continueReviewPublish: 'Continue - Review and publish',
    costSummary: 'Cost summary',
    selectedPortals: 'Selected portals',
    noPortalSelected: 'No portal selected',
    breakdown: 'Breakdown',
    freeFreemiumPortals: 'Free/freemium portals',
    estimatedTotal: 'Estimated total',
    costWarning: 'Costs are estimates. The final cost is confirmed when publishing on each portal.',
    aiRecommendation: 'AI recommendation',
    currentVacancyRecommendation: 'For your current vacancy, Sofi recommends prioritizing:',
    applySuggestedSelection: 'Apply suggested selection',
    confirmPublishTitle: 'Confirm and publish',
    confirmPublishInfo: 'Review the summary before publishing. Once confirmed, Sofi will send the vacancy to each selected portal.',
    vacancy: 'Vacancy',
    noName: 'No name',
    noLocation: 'No location',
    selectedPortalsCount: 'selected portals',
    publicationStatus: 'Publication status',
    pendingStart: 'Pending start',
    queued: 'Queued',
    publishing: 'Publishing...',
    inProgress: 'In progress',
    publishedOk: 'Published successfully',
    published: 'Published',
    modifySelection: 'Modify selection',
    startNewVacancy: 'Start new vacancy',
    processing: 'Processing...',
    publishVacancyAction: 'Publish vacancy',
    finalSummary: 'Final summary',
    freePortalsToPublish: 'Free portals to publish',
    paidPortalsToPublish: 'Paid portals to publish',
    totalToPay: 'Total to pay',
    paymentMethod: 'Payment method',
    noPaymentRequired: 'No payment required',
    corporateCard: 'Corporate card ****4821',
    bankTransfer: 'Bank transfer',
    sofiCredit: 'Sofi credit (available balance: MX$ 5,000)',
    publicationValidity: 'Publication validity',
    paidPortalsPublishUntil: 'Paid portals publish until this date',
    languageSwitch: 'Change language',
    adminSignIn: 'Admin sign in',
    restrictedAccess: 'Restricted access',
    credentialsSaved: 'Credentials saved successfully',
    credentialsSaveError: 'Error saving credentials',
    portalCredentialsHelp: 'Please enter your credentials to publish on this portal.',
    usernameOrEmail: 'Username or email',
    requiredField: 'This field is required',
    secureCredentials: 'Your credentials are stored encrypted and securely.',
    cancel: 'Cancel',
    saving: 'Saving...',
    saveCredentials: 'Save credentials',
  },
};

const applyTheme = (theme) => {
  if (typeof document === 'undefined') return;
  document.documentElement.classList.toggle('dark', theme === 'dark');
};

export function AppSettingsProvider({ children }) {
  const [theme, setTheme] = useState('light');
  const [locale, setLocale] = useState('es');

  useEffect(() => {
    const storedTheme = localStorage.getItem(STORAGE_KEYS.theme);
    const storedLocale = localStorage.getItem(STORAGE_KEYS.locale);

    const initialTheme = storedTheme === 'dark' ? 'dark' : 'light';
    const initialLocale = storedLocale === 'en' ? 'en' : 'es';

    setTheme(initialTheme);
    setLocale(initialLocale);
    applyTheme(initialTheme);
  }, []);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.theme, theme);
    applyTheme(theme);
  }, [theme]);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEYS.locale, locale);
  }, [locale]);

  const toggleTheme = () => setTheme((current) => (current === 'light' ? 'dark' : 'light'));
  const toggleLocale = () => setLocale((current) => (current === 'es' ? 'en' : 'es'));

  const t = (key) => translations[locale][key] ?? translations.es[key] ?? key;

  return (
    <AppSettingsContext.Provider value={{ theme, locale, toggleTheme, toggleLocale, t }}>
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error('useAppSettings must be used within AppSettingsProvider');
  }
  return context;
}
