export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'sofi-purple': 'var(--color-purple)',
        'sofi-purple-light': 'var(--color-purple-light)',
        'sofi-purple-dark': 'var(--color-purple-dark)',
        'sofi-teal': 'var(--color-teal)',
        'sofi-teal-light': 'var(--color-teal-light)',
        'sofi-teal-dark': 'var(--color-teal-dark)',
        'purple': 'var(--color-purple)',
        'purple-dark': 'var(--color-purple-dark)',
        'purple-light': 'var(--color-purple-light)',
        'teal': 'var(--color-teal)',
        'teal-dark': 'var(--color-teal-dark)',
        'teal-light': 'var(--color-teal-light)',
        'bg-main': 'var(--color-bg-main)',
        'card': 'var(--color-card)',
        'border-main': 'var(--color-border-main)',
        'text-main': 'var(--color-text-main)',
        'text-muted': 'var(--color-text-muted)',
        'warn': 'var(--color-warn)',
        'warn-text': 'var(--color-warn-text)',
        'info': 'var(--color-info)',
        'info-text': 'var(--color-info-text)',
        'amber-soft': 'var(--color-amber-soft)',
        'amber-text': 'var(--color-amber-text)',
        'status-free': 'var(--color-status-free)',
        'status-paid': 'var(--color-status-paid)',
        'status-freemium': 'var(--color-status-freemium)',
      },
      fontFamily: {
        'dm-sans': ['DM Sans', 'sans-serif'],
        'dm-mono': ['DM Mono', 'monospace'],
      },
      animation: {
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      transitionDuration: {
        '150': '150ms',
      },
      spacing: {
        'safe': 'max(1rem, env(safe-area-inset-bottom))',
      },
    },
  },
  plugins: [],
};
